### ISSUE TITLE
implement caom2-artifact-sync tool

### ISSUE THREAD

**Issue by pdowler** [opencadc/caom2db#36]
Incremental discovery based on Artifact.lastModified; compare Artifact metadata to metadata from storage system; persist download "jobs" as HarvestSkipURI instances

Multi-threaded file retrieval using batches of Worker(HarvestSkipURI) and a thread pool; pool size 1-8 should suffice

**Comment by severingaudet** [comment]
![img_0049](https://user-images.githubusercontent.com/7774557/28341726-baa8bef6-6bc9-11e7-9788-5ead1ad12a5a.jpg)
Whiteboard discussion image.

**Comment by severingaudet** [comment]
From the July 18 meeting: need a mechanism (could be hardcoded) to only retrieve legacy data files (FOS, FOC, GHRS, WFPC1) for the functionality test.

**Comment by pdowler** [comment]
initial version (caom2-artifact-sync) implemented
