### ISSUE TITLE
Change caom2-remove so '--source' parameter is optional

### ISSUE THREAD

**Issue by hjeeves** [opencadc/caom2db#99]
So that collections that do not have HarvestState records can be removed.

**Comment by pdowler** [comment]
If the API of HarvestStateDAO was augmented to include something like:

List<HarvestState> find(String collection)

then tools like caom2-remove could find the state and tell the user where the collection came from. Then the --source option would not be needed at all.

As an extra, HarvestState records for other classes (currently: the 3 ReadAccess types) could also be used to implement extra cleanup in future.

**Comment by pdowler** [comment]
made --source optional 
added explicit --nosource to avoid unintentional mistakes
caom2-remove-1.1
